export const data = {
  userDetails: {
    name: "Radhey",
    plant: "India",
    department: "Engineering",
    designation: "software",
    mobileNumber: "8904583792",
  },
  /* myOrders: [
    {
      id: "",
      date: "08/11/2020",
      number: "100986",
      status: "placed",
    },
    {
      id: "",
      date: "15/11/2020",
      number: "68403",
      status: "dispatched",
    },
  ], */
  myOrders: {
    orderList: [
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Invoiced",
        distributionCode: "10",
        division: "01",
        gstInvNo: "MH2001001775",
        invDate: "07/12/2020",
        invNo: "1391501464",
        oneTimeService: "0",
        ordDate: "07/12/2020",
        orderNo: "0056980948",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Completely billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Delivered",
        distributionCode: "10",
        division: "01",
        gstInvNo: "MH2001001774",
        invDate: "07/12/2020",
        invNo: "1391501463",
        oneTimeService: "2",
        ordDate: "07/12/2020",
        orderNo: "0056980948",
        salesOrg: "1000",
        shipmentFlag: "1",
        shipmentID: "1000718172",
        status: "Completely billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "At Dispatch Bay",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "07/12/2020",
        orderNo: "0056980950",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "07/12/2020",
        orderNo: "0056980964",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "07/12/2020",
        orderNo: "0056980974",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "09/12/2020",
        orderNo: "0056981052",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "09/12/2020",
        orderNo: "0056981053",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "09/12/2020",
        orderNo: "0056981054",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "09/12/2020",
        orderNo: "0056981056",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "09/12/2020",
        orderNo: "0056981057",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "09/12/2020",
        orderNo: "0056981075",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "10/12/2020",
        orderNo: "0056981094",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "10/12/2020",
        orderNo: "0056981095",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "10/12/2020",
        orderNo: "0056981100",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "11/12/2020",
        orderNo: "0056981132",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "11/12/2020",
        orderNo: "0056981134",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "11/12/2020",
        orderNo: "0056981135",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "13/12/2020",
        orderNo: "0056981164",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "25",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "13/12/2020",
        orderNo: "0056981179",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "25",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "13/12/2020",
        orderNo: "0056981180",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "13/12/2020",
        orderNo: "0056981181",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "01",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "14/12/2020",
        orderNo: "0056981188",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
      {
        custID: "111801",
        dealerCode: "0000111801",
        detailStatus: "Order Placed",
        distributionCode: "10",
        division: "25",
        gstInvNo: "",
        invDate: "",
        invNo: "",
        oneTimeService: "0",
        ordDate: "14/12/2020",
        orderNo: "0056981197",
        salesOrg: "1000",
        shipmentFlag: "",
        shipmentID: "",
        status: "Not yet billed",
      },
    ],
    statusCode: "200",
    statusMessage: "success",
  },
  /*   myOrderDetails: {
    tableHead: ["Material/Desc.", "Order Qty", "Invoice Qty"],
    tableData: [
      {
        orderQuantity: 4,
        invoiceQuantity: 0,
        material: {
          description: "AP TrueCare asdfasdf  asdfasdfsfasd asdfa ssad",
          litres: 20,
        },
      },
      {
        orderQuantity: 12,
        invoiceQuantity: 0,
        material: { description: "AP Wall ONS", litres: 4 },
      },
      {
        orderQuantity: 2,
        invoiceQuantity: 0,
        material: { description: "Trac UNO", litres: 15 },
      },
      {
        orderQuantity: 3,
        invoiceQuantity: 0,
        material: { description: "Apcolite GLOSS", litres: 10 },
      },
    ],
  }, */
  myOrderDetails: {
    dealerOrderItem: [
      {
        billedQuantity: "2",
        currentStatus: "Completely billed",
        distributionChannel: "10",
        gstInvno: "MH2001001774",
        invoiceDate: "12/07/2020",
        invoiceNumber: "1391501463",
        material: "00129097320",
        materialDescription: "AP APEX AB2 20 LT",
        orderDate: "12/07/2020",
        orderNumber: "56980948",
        orderQuantity: "2",
      },
      {
        billedQuantity: "3",
        currentStatus: "Completely billed",
        distributionChannel: "10",
        gstInvno: "MH2001001775",
        invoiceDate: "12/07/2020",
        invoiceNumber: "1391501464",
        material: "00260912320",
        materialDescription: "AP APCO GL ENML WT BR WHITE 20 LT",
        orderDate: "12/07/2020",
        orderNumber: "56980948",
        orderQuantity: "3",
      },
    ],
    statusCode: "200",
    statusMessage: "success",
  },
  cartItems: [
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "234556745",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 5,
    },
    {
      src: require("../assets/cart-items/ap2.png"),
      id: "485793434",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 25,
    },
    {
      src: require("../assets/cart-items/ap3.png"),
      id: "1095u74654",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 8,
    },
    {
      src: require("../assets/cart-items/ap4.png"),
      id: "658795345",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 12,
    },
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "12346657",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 2,
    },
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "12346657",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 2,
    },
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "12346657",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 2,
    },
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "12346657",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 2,
    },
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "12346657",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 2,
    },
    {
      src: require("../assets/cart-items/ap1.png"),
      id: "12346657",
      name: "asdfa asdfasdathend sddtrjhoimdfbi",
      quantity: 2,
    },
  ],
};
